In [1]:
import os
os.chdir("I:\\all data")

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data=pd. read_excel("order data.xlsx", 'OrderBreakdown') #loading second sheet

In [4]:
data.head()

,Order ID,Product Name,Discount,Sales,Profit,Quantity,Category,Sub-Category
0,BN-2011-7407039,"Enermax Note Cards, Premium",0.5,45,-26,3,Office Supplies,Paper
1,AZ-2011-9050313,"Dania Corner Shelving, Traditional",0.0,854,290,7,Furniture,Bookcases
2,AZ-2011-6674300,"Binney & Smith Sketch Pad, Easy-Erase",0.0,140,21,3,Office Supplies,Art
3,BN-2011-2819714,"Boston Markers, Easy-Erase",0.5,27,-22,2,Office Supplies,Art
4,BN-2011-2819714,"Eldon Folders, Single Width",0.5,17,-1,2,Office Supplies,Storage

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8047 entries, 0 to 8046
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      8047 non-null   object
 1   Product Name  8047 non-null   object
 2   Discount      8047 non-null   float64
 3   Sales         8047 non-null   int64
 4   Profit        8047 non-null   int64
 5   Quantity      8047 non-null   int64
 6   Category      8047 non-null   object
 7   Sub-Category  8047 non-null   object
dtypes: float64(1), int64(3), object(4)
memory usage: 503.1+ KB

In [6]:
data.columns

Index(['Order ID', 'Product Name', 'Discount', 'Sales', 'Profit', 'Quantity',
       'Category', 'Sub-Category'],
      dtype='object')

In [7]:
data.shape

(8047, 8)

In [8]:
data.describe()

          Discount        Sales       Profit     Quantity
count  8047.000000  8047.000000  8047.000000  8047.000000
mean      0.110047   291.845657    35.198211     3.772089
std       0.181773   485.212156   178.125844     2.203369
min       0.000000     3.000000 -3060.000000     1.000000
25%       0.000000    48.000000     1.000000     2.000000
50%       0.000000   117.000000    14.000000     3.000000
75%       0.100000   313.000000    47.000000     5.000000
max       0.850000  6517.000000  2476.000000    14.000000

In [9]:
data.columns = ['Order_Id','Product_Name','Discount','Sales','Profit','Quantity','Category','Sub_Categorty']
data

,Order_Id,Product_Name,Discount,Sales,Profit,Quantity,Category,Sub_Categorty
0,BN-2011-7407039,"Enermax Note Cards, Premium",0.5,45,-26,3,Office Supplies,Paper
1,AZ-2011-9050313,"Dania Corner Shelving, Traditional",0.0,854,290,7,Furniture,Bookcases
2,AZ-2011-6674300,"Binney & Smith Sketch Pad, Easy-Erase",0.0,140,21,3,Office Supplies,Art
3,BN-2011-2819714,"Boston Markers, Easy-Erase",0.5,27,-22,2,Office Supplies,Art
4,BN-2011-2819714,"Eldon Folders, Single Width",0.5,17,-1,2,Office Supplies,Storage
...,...,...,...,...,...,...,...,...
8042,AZ-2014-766953,"Ikea Stackable Bookrack, Traditional",0.0,245,91,2,Furniture,Bookcases
8043,BN-2014-4140795,"BIC Pencil Sharpener, Fluorescent",0.5,30,-10,2,Office Supplies,Art
8044,BN-2014-4140795,"Avery Binder Covers, Recycled",0.5,23,-6,4,Office Supplies,Binders
8045,BN-2014-4140795,"StarTech Phone, Red",0.5,108,-19,3,Technology,Machines
8046,AZ-2014-766953,"Motorola Audio Dock, VoIP",0.0,867,251,5,Technology,Phones

In [10]:
data['Category'].value_counts()

Office Supplies    5286
Technology         1523
Furniture          1238
Name: Category, dtype: int64

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8047 entries, 0 to 8046
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_Id       8047 non-null   object
 1   Product_Name   8047 non-null   object
 2   Discount       8047 non-null   float64
 3   Sales          8047 non-null   int64
 4   Profit         8047 non-null   int64
 5   Quantity       8047 non-null   int64
 6   Category       8047 non-null   object
 7   Sub_Categorty  8047 non-null   object
dtypes: float64(1), int64(3), object(4)
memory usage: 503.1+ KB

In [12]:
data.isnull().sum()

Order_Id         0
Product_Name     0
Discount         0
Sales            0
Profit           0
Quantity         0
Category         0
Sub_Categorty    0
dtype: int64

In [13]:
data['Sub_Categorty'].value_counts()

Art            1152
Binders        1059
Storage        1051
Phones          453
Bookcases       391
Furnishings     389
Chairs          383
Paper           374
Labels          372
Accessories     368
Copiers         367
Fasteners       350
Supplies        347
Envelopes       346
Machines        335
Appliances      235
Tables           75
Name: Sub_Categorty, dtype: int64

In [14]:
data[data['Sub_Categorty']=='Binders']

,Order_Id,Product_Name,Discount,Sales,Profit,Quantity,Category,Sub_Categorty
18,AZ-2011-6712797,"Ibico Hole Reinforcements, Recycled",0.0,22,7,3,Office Supplies,Binders
23,AZ-2011-5702370,"Ibico Index Tab, Clear",0.0,17,6,2,Office Supplies,Binders
25,BN-2011-4913858,"Wilson Jones Hole Reinforcements, Durable",0.5,9,-3,3,Office Supplies,Binders
40,AZ-2011-1816950,"Acco Binding Machine, Economy",0.5,26,-11,1,Office Supplies,Binders
41,AZ-2011-5342265,"Wilson Jones Binding Machine, Clear",0.0,145,44,3,Office Supplies,Binders
...,...,...,...,...,...,...,...,...
8014,AZ-2014-6752912,"Cardinal Binding Machine, Economy",0.0,100,28,2,Office Supplies,Binders
8021,BN-2014-3913645,"Avery 3-Hole Punch, Economy",0.5,56,0,4,Office Supplies,Binders
8037,AZ-2014-436448,"Acco Binder, Economy",0.0,45,6,3,Office Supplies,Binders
8041,AZ-2014-7604524,"Wilson Jones Index Tab, Economy",0.0,32,8,5,Office Supplies,Binders
8044,BN-2014-4140795,"Avery Binder Covers, Recycled",0.5,23,-6,4,Office Supplies,Binders

In [21]:
#data[(data['State']=='England') & (data['Region']=='North')]

In [16]:
data[(data['Sales']>200) & (data['Profit']>50)]

,Order_Id,Product_Name,Discount,Sales,Profit,Quantity,Category,Sub_Categorty
1,AZ-2011-9050313,"Dania Corner Shelving, Traditional",0.0,854,290,7,Furniture,Bookcases
6,AZ-2011-617423,"Sanford Canvas, Fluorescent",0.0,207,77,4,Office Supplies,Art
9,AZ-2011-2918397,"Smead Lockers, Industrial",0.1,716,143,4,Office Supplies,Storage
20,AZ-2011-9927716,"Hon Chairmat, Adjustable",0.0,290,70,5,Furniture,Chairs
21,AZ-2011-5702370,"Ikea Stackable Bookrack, Traditional",0.1,552,165,5,Furniture,Bookcases
...,...,...,...,...,...,...,...,...
8032,AZ-2014-3870231,"Canon Fax and Copier, Laser",0.0,1913,899,10,Technology,Copiers
8038,AZ-2014-1412225,"Fellowes Shelving, Single Width",0.0,289,75,5,Office Supplies,Storage
8039,AZ-2014-4217323,"Fellowes Lockers, Wire Frame",0.1,557,217,3,Office Supplies,Storage
8042,AZ-2014-766953,"Ikea Stackable Bookrack, Traditional",0.0,245,91,2,Furniture,Bookcases
8046,AZ-2014-766953,"Motorola Audio Dock, VoIP",0.0,867,251,5,Technology,Phones

In [17]:
data[(data['Sales']>800) & (data['Profit']>200)]

,Order_Id,Product_Name,Discount,Sales,Profit,Quantity,Category,Sub_Categorty
1,AZ-2011-9050313,"Dania Corner Shelving, Traditional",0.00,854,290,7,Furniture,Bookcases
46,AZ-2011-8034411,"Bush Classic Bookcase, Traditional",0.00,825,338,2,Furniture,Bookcases
109,AZ-2011-5676694,"Dania Classic Bookcase, Traditional",0.00,822,353,2,Furniture,Bookcases
117,BN-2011-307477,"SAFCO Executive Leather Armchair, Black",0.10,4544,1868,11,Furniture,Chairs
153,AZ-2011-7903656,"Safco Classic Bookcase, Traditional",0.00,1314,342,3,Furniture,Bookcases
...,...,...,...,...,...,...,...,...
8003,AZ-2014-338779,"Hamilton Beach Stove, White",0.10,973,205,2,Office Supplies,Appliances
8012,AZ-2014-6752912,"Lesro Round Table, Rectangular",0.35,1461,202,5,Furniture,Tables
8013,AZ-2014-6752912,"Hoover Microwave, White",0.10,1104,209,4,Office Supplies,Appliances
8032,AZ-2014-3870231,"Canon Fax and Copier, Laser",0.00,1913,899,10,Technology,Copiers
8046,AZ-2014-766953,"Motorola Audio Dock, VoIP",0.00,867,251,5,Technology,Phones

In [20]:
data[(data['Sales']>800) & (data['Discount']>0.3)]

,Order_Id,Product_Name,Discount,Sales,Profit,Quantity,Category,Sub_Categorty
10,BN-2011-3248724,"Ikea Classic Bookcase, Metal",0.60,987,-1012,6,Furniture,Bookcases
50,AZ-2011-8034411,"Rogers Lockers, Single Width",0.40,889,59,7,Office Supplies,Storage
113,BN-2011-493873,"Sauder Classic Bookcase, Pine",0.50,875,-577,4,Furniture,Bookcases
128,AZ-2011-2270958,"Barricks Round Table, with Bottom Storage",0.50,1003,-943,4,Furniture,Tables
402,AZ-2011-2598415,"Bevis Coffee Table, with Bottom Storage",0.35,827,-395,4,Furniture,Tables
...,...,...,...,...,...,...,...,...
7889,BN-2014-7539265,"Canon Fax Machine, Color",0.50,1279,-640,8,Technology,Copiers
7970,BN-2014-5013417,"Chromcraft Wood Table, with Bottom Storage",0.35,941,-203,3,Furniture,Tables
7994,BN-2014-2616164,"KitchenAid Refrigerator, Black",0.50,1582,-443,6,Office Supplies,Appliances
7996,BN-2014-6319094,"Fellowes Lockers, Wire Frame",0.50,929,-93,9,Office Supplies,Storage
8012,AZ-2014-6752912,"Lesro Round Table, Rectangular",0.35,1461,202,5,Furniture,Tables

In [22]:
data[(data['Category']=='Furniture') & (data['Sub_Categorty']=='Tables')]

,Order_Id,Product_Name,Discount,Sales,Profit,Quantity,Category,Sub_Categorty
14,AZ-2011-6439906,"Bevis Training Table, with Bottom Storage",0.60,268,-342,2,Furniture,Tables
114,BN-2011-493873,"Barricks Coffee Table, Fully Assembled",0.70,273,-500,3,Furniture,Tables
128,AZ-2011-2270958,"Barricks Round Table, with Bottom Storage",0.50,1003,-943,4,Furniture,Tables
362,BN-2011-7737747,"Chromcraft Wood Table, with Bottom Storage",0.35,627,-135,2,Furniture,Tables
402,AZ-2011-2598415,"Bevis Coffee Table, with Bottom Storage",0.35,827,-395,4,Furniture,Tables
...,...,...,...,...,...,...,...,...
7062,AZ-2014-8568817,"Barricks Round Table, Rectangular",0.35,1622,-624,5,Furniture,Tables
7138,BN-2014-2098637,"Bevis Coffee Table, Fully Assembled",0.35,623,-192,3,Furniture,Tables
7302,BN-2014-6471690,"Chromcraft Round Table, Adjustable Height",0.35,610,-66,2,Furniture,Tables
7970,BN-2014-5013417,"Chromcraft Wood Table, with Bottom Storage",0.35,941,-203,3,Furniture,Tables
8012,AZ-2014-6752912,"Lesro Round Table, Rectangular",0.35,1461,202,5,Furniture,Tables

In [23]:
data[(data['Category']=='Furniture') & (data['Discount']>0.3)]

,Order_Id,Product_Name,Discount,Sales,Profit,Quantity,Category,Sub_Categorty
10,BN-2011-3248724,"Ikea Classic Bookcase, Metal",0.60,987,-1012,6,Furniture,Bookcases
14,AZ-2011-6439906,"Bevis Training Table, with Bottom Storage",0.60,268,-342,2,Furniture,Tables
51,BN-2011-7883641,"Harbour Creations Swivel Stool, Set of Two",0.60,73,-57,1,Furniture,Chairs
52,BN-2011-7883641,"Office Star Bag Chairs, Set of Two",0.60,69,-95,3,Furniture,Chairs
113,BN-2011-493873,"Sauder Classic Bookcase, Pine",0.50,875,-577,4,Furniture,Bookcases
...,...,...,...,...,...,...,...,...
7970,BN-2014-5013417,"Chromcraft Wood Table, with Bottom Storage",0.35,941,-203,3,Furniture,Tables
7978,BN-2014-5182753,"Advantus Photo Frame, Durable",0.60,20,-22,1,Furniture,Furnishings
7988,BN-2014-9956954,"Harbour Creations Bag Chairs, Black",0.60,24,-30,1,Furniture,Chairs
8010,BN-2014-5301206,"Novimex Rocking Chair, Black",0.50,516,-392,8,Furniture,Chairs
8012,AZ-2014-6752912,"Lesro Round Table, Rectangular",0.35,1461,202,5,Furniture,Tables

In [27]:
data[(data['Sales']>1000) & (data['Quantity']>5) & (data['Profit']>500)]

,Order_Id,Product_Name,Discount,Sales,Profit,Quantity,Category,Sub_Categorty
117,BN-2011-307477,"SAFCO Executive Leather Armchair, Black",0.10,4544,1868,11,Furniture,Chairs
175,AZ-2011-823697,"Hoover Stove, Red",0.10,3070,1364,6,Office Supplies,Appliances
711,AZ-2011-5059692,"Cisco Smart Phone, Cordless",0.10,5277,1759,9,Technology,Phones
750,AZ-2011-7213826,"Nokia Smart Phone, Cordless",0.00,4453,1425,7,Technology,Phones
868,AZ-2011-5313166,"Hamilton Beach Stove, Silver",0.00,6517,2476,12,Office Supplies,Appliances
...,...,...,...,...,...,...,...,...
7518,AZ-2014-3332040,"Brother Copy Machine, Color",0.00,1846,794,7,Technology,Copiers
7632,AZ-2014-9173852,"Epson Printer, Durable",0.15,2457,665,11,Technology,Machines
7750,AZ-2014-1598982,"Hewlett Copy Machine, Color",0.00,1591,541,6,Technology,Copiers
7937,AZ-2014-4842242,"Ikea Library with Doors, Pine",0.00,2553,843,7,Furniture,Bookcases
8032,AZ-2014-3870231,"Canon Fax and Copier, Laser",0.00,1913,899,10,Technology,Copiers