In [1]:
import os
os.chdir("C:\\Users\\SHAILESH TIWARI\\Python Files\\DataSources")

In [ ]:
# dimensionality reduction used to reduce the number of dimensions.
# check p-value first to reduce variables then after use dimensionality reduction(option)

In [2]:
os.getcwd()

'C:\\Users\\SHAILESH TIWARI\\Python Files\\DataSources'

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("Bank-data.csv")

In [5]:
df.head(10)

   Index  interest_rate  credit  Gender  previous  duration Churn
0      0          1.334       0       1         0       117    no
1      1          0.767       0       0         1       274   yes
2      2          4.858       0       1         0       167    no
3      3          4.120       0       0         0       686   yes
4      4          4.856       0       1         0       159    no
5      5          0.899       0       0         0       120    no
6      6          4.962       0       0         0       337    no
7      7          4.858       0       1         0       640    no
8      8          4.962       0       0         0       663   yes
9      9          4.865       0       0         0       403    no

In [6]:
df['Churn']= df['Churn'].astype('category')
df['Churn']= df['Churn'].cat.codes        # applyied encoding on churn column

In [7]:
df

     Index  interest_rate  credit  Gender  previous  duration  Churn
0        0          1.334       0       1         0       117      0
1        1          0.767       0       0         1       274      1
2        2          4.858       0       1         0       167      0
3        3          4.120       0       0         0       686      1
4        4          4.856       0       1         0       159      0
..     ...            ...     ...     ...       ...       ...    ...
513    513          1.334       0       1         0       204      0
514    514          0.861       0       0         1       806      1
515    515          0.879       0       0         0       290      0
516    516          0.877       0       0         1       473      1
517    517          4.965       0       0         0       142      0

[518 rows x 7 columns]

In [8]:
x = df.iloc[:,0:6].values

In [9]:
x

array([[  0.   ,   1.334,   0.   ,   1.   ,   0.   , 117.   ],
       [  1.   ,   0.767,   0.   ,   0.   ,   1.   , 274.   ],
       [  2.   ,   4.858,   0.   ,   1.   ,   0.   , 167.   ],
       ...,
       [515.   ,   0.879,   0.   ,   0.   ,   0.   , 290.   ],
       [516.   ,   0.877,   0.   ,   0.   ,   1.   , 473.   ],
       [517.   ,   4.965,   0.   ,   0.   ,   0.   , 142.   ]])

In [10]:
y = df.iloc[:,6].values

In [11]:
y

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0], dtype=int8)

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [13]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)

C:\Users\SHAILESH TIWARI\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [14]:
y_pred = logmodel.predict(x_test)

In [15]:
y_pred

array([0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [16]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[46, 10],
       [ 8, 40]], dtype=int64)

In [17]:
#accuracy score
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8269230769230769

In [18]:
x

array([[  0.   ,   1.334,   0.   ,   1.   ,   0.   , 117.   ],
       [  1.   ,   0.767,   0.   ,   0.   ,   1.   , 274.   ],
       [  2.   ,   4.858,   0.   ,   1.   ,   0.   , 167.   ],
       ...,
       [515.   ,   0.879,   0.   ,   0.   ,   0.   , 290.   ],
       [516.   ,   0.877,   0.   ,   0.   ,   1.   , 473.   ],
       [517.   ,   4.965,   0.   ,   0.   ,   0.   , 142.   ]])

In [19]:
from sklearn.decomposition import PCA
pca = PCA(n_components=None)  # based on columns
x_train_n = pca.fit_transform(x_train)
x_test_n = pca.fit_transform(x_test)

In [20]:
pd.DataFrame(x_train)

         0      1    2    3    4      5
0    513.0  1.334  0.0  1.0  0.0  204.0
1    163.0  4.966  0.0  0.0  0.0  264.0
2    511.0  4.965  0.0  0.0  0.0  479.0
3    243.0  1.281  0.0  1.0  0.0   69.0
4    219.0  4.859  0.0  1.0  0.0   51.0
..     ...    ...  ...  ...  ...    ...
409    5.0  0.899  0.0  0.0  0.0  120.0
410  203.0  1.365  0.0  0.0  0.0  815.0
411  444.0  1.039  0.0  0.0  1.0  655.0
412  316.0  4.963  0.0  0.0  0.0  988.0
413  378.0  0.714  0.0  0.0  0.0  805.0

[414 rows x 6 columns]

In [21]:
pd.DataFrame(x_train_n)

              0           1         2         3         4         5
0   -178.387931 -258.232048 -1.337912  0.777997 -0.183451  0.011461
1   -132.481004   93.897091  1.933842 -0.262101 -0.018749 -0.030776
2     96.309557 -245.195379  2.344130 -0.194083 -0.051583  0.013906
3   -324.113112    6.133296 -1.704565  0.724168 -0.160534 -0.023255
4   -343.062389   29.395493  1.836359  0.745417  0.079479  0.008461
..          ...         ...       ...       ...       ...       ...
409 -282.704016  245.987303 -2.318361 -0.321423 -0.275715 -0.091367
410  419.681020   76.034829 -1.523517 -0.291370 -0.245068 -0.052855
411  269.480211 -171.191620 -1.680658 -0.358892  0.691349 -0.046064
412  597.075122  -29.928503  2.217087 -0.245429 -0.013225 -0.001762
413  416.711196  -99.226076 -1.985984 -0.259390 -0.308600 -0.038483

[414 rows x 6 columns]

In [22]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2) # define by yourself
x_train_2 = pca.fit_transform(x_train)
x_test_2 = pca.fit_transform(x_test)

In [23]:
pd.DataFrame(x_train_2)

              0           1
0   -178.387931 -258.232048
1   -132.481004   93.897091
2     96.309557 -245.195379
3   -324.113112    6.133296
4   -343.062389   29.395493
..          ...         ...
409 -282.704016  245.987303
410  419.681020   76.034829
411  269.480211 -171.191620
412  597.075122  -29.928503
413  416.711196  -99.226076

[414 rows x 2 columns]

In [24]:
explained_variance = pca.explained_variance_ratio_

In [25]:
pd.DataFrame(explained_variance)

          0
0  0.745514
1  0.254446

In [26]:
x_train_2

array([[-1.78387931e+02, -2.58232048e+02],
       [-1.32481004e+02,  9.38970906e+01],
       [ 9.63095568e+01, -2.45195379e+02],
       [-3.24113112e+02,  6.13329614e+00],
       [-3.43062389e+02,  2.93954927e+01],
       [ 4.23167430e+02, -2.35076392e+02],
       [-2.48210512e+02, -1.48378674e+01],
       [-2.54980685e+02,  7.89696709e+01],
       [-2.34235072e+02, -1.88413067e+02],
       [ 1.51828546e+02, -7.78092325e+00],
       [ 5.53444101e+02,  1.34453120e+02],
       [-6.79864438e+01, -6.66479864e+01],
       [ 7.03122116e+02, -1.03733708e+02],
       [ 3.69812617e+02, -3.02596218e+00],
       [ 6.15595844e+01, -1.27499439e+02],
       [-6.79021760e+01,  1.55536963e+02],
       [ 1.32305686e+02, -1.44673817e+02],
       [ 3.26474573e+00,  3.27107278e+00],
       [-3.29695312e+02,  1.70044974e+02],
       [ 1.47811177e+02,  1.17162772e+02],
       [-2.87935575e+01, -2.20199109e+02],
       [-1.88552333e+02,  6.96276458e+01],
       [-1.77984740e+01, -2.44777684e+02],
       [-7.34269783e+01,  2.18362319e+02],
       [ 1.45663592e+03,  1.72724321e+02],
       [-2.42785542e+02, -1.99769846e+02],
       [-2.75746674e+02,  2.22251619e+02],
       [-2.85445169e+02,  1.39792394e+02],
       [-8.32591214e+01, -3.52361164e+01],
       [-1.86609673e+02, -7.84180988e+01],
       [ 4.43701181e+02, -1.73201824e+02],
       [-3.39964192e+02,  1.51618098e+02],
       [-2.40178276e+02, -2.64712946e+02],
       [-1.47091342e+02,  2.33423117e+02],
       [-2.54234576e+02, -8.91365417e+01],
       [-4.53227867e+01, -8.27477046e+01],
       [-3.61318270e+01,  1.86833449e+02],
       [-2.45903736e+02,  5.23124377e+01],
       [-1.41321776e+02, -1.09621371e+02],
       [-1.92922081e+02,  1.53519821e+02],
       [-2.14843797e+02,  2.65344234e+01],
       [-1.30690226e+02,  1.49008666e+02],
       [-4.90299422e+01, -1.39947314e+02],
       [ 1.78493711e+02, -4.87440405e+01],
       [-7.28652105e+01,  2.04373515e+02],
       [ 3.22163722e+02, -2.12106167e+02],
       [-1.21533109e+02,  1.20353504e+02],
       [-1.57444955e+02, -2.56390284e+02],
       [-2.00715676e+02, -1.00997723e+02],
       [ 2.19569263e+01, -1.63117161e+02],
       [ 6.33668593e+02, -1.68576314e+02],
       [ 6.21469554e+02,  1.35183212e+02],
       [-1.04141576e+02,  8.60233291e+01],
       [-1.05264618e+01,  2.27291300e+01],
       [-2.42271999e+02,  8.64854851e+01],
       [ 1.01960829e+02, -8.68451533e+01],
       [ 2.27723287e-01,  2.53350353e+02],
       [ 1.97730116e+02, -1.29032309e+02],
       [ 3.44056894e+01,  2.24695038e+02],
       [ 3.32316169e+02, -2.15701679e+02],
       [-2.53680028e+02,  1.96115184e+02],
       [ 7.49161259e+02, -7.88652326e+01],
       [ 5.09086218e+02, -1.56564802e+02],
       [ 2.28946569e+02,  1.15416998e+02],
       [-7.48000503e+01,  5.31755240e+01],
       [-3.30731318e+02, -1.03216433e+02],
       [-1.33857779e+02, -4.62709548e+01],
       [-6.62122524e+01,  8.85470364e+01],
       [ 9.18129707e+02,  2.49982927e+01],
       [-2.90979780e+02,  3.46340420e+00],
       [ 1.21461591e+00, -1.69955366e+02],
       [ 1.35949420e+01,  1.44795695e+02],
       [-1.29944509e+02,  2.30108370e+02],
       [-2.84940740e+02, -2.23140118e+01],
       [-1.46115659e+02,  1.34378084e+02],
       [-4.74125186e+01, -5.77338290e+00],
       [-2.33127339e+02, -1.16310596e+02],
       [-1.09081803e+02,  2.33948573e+02],
       [-2.39807889e+02,  1.74655570e+02],
       [ 7.96086453e+00,  1.35562156e+02],
       [-2.33651371e+02,  1.70894772e+02],
       [ 2.52445767e+02,  1.28370409e+02],
       [ 8.68762707e+01, -2.34569911e+02],
       [ 7.76315319e+01,  9.53254524e+01],
       [-2.30493266e+02,  1.67018564e+02],
       [-2.76979417e+02, -7.10337620e+01],
       [-2.75665643e+02,  2.20249562e+02],
       [-2.29020563e+02,  2.05109091e+02],
       [ 4.49010138e+02,  1.18249518e+02],
       [-1.91460973e+02,  1.74651554e+01],
       [-6.53578212e+01,  2.41708691e+02],
       [-2.81016322e+02, -7.01950670e+01],
       [-1.96056984e+02, -2.41925073e+02],
       [-1.27204817e+02, -1.62097212e+02],
       [-4.67106485e+01, -1.47859586e+02],
       [ 5.86699150e+02,  1.28779167e+02],
       [-2.31059084e+02,  2.06028067e+02],
       [ 2.98222472e+01, -1.09758785e+02],
       [-1.20727476e+02,  7.53537850e+01],
       [-1.41645896e+02,  1.72591659e+02],
       [-3.32589601e+02, -2.31394147e+02],
       [-1.87375980e+02, -3.44132839e+01],
       [-9.10914691e+01,  2.09646465e+02],
       [-2.25453330e+02,  1.41200810e+02],
       [-1.29795365e+01, -1.40496376e+02],
       [-3.30329258e+02,  1.35991266e+02],
       [-2.44715752e+02,  1.22416524e+02],
       [-3.83993221e+02,  5.17710411e+01],
       [-2.06079922e+02, -4.21696945e+01],
       [ 2.37269627e+01,  1.70993677e+01],
       [ 5.65855389e+02, -1.57263531e-01],
       [-1.47572850e+02,  2.45413446e+02],
       [ 9.54959697e+01, -1.50155398e+02],
       [ 1.44536182e+02, -1.50184738e+02],
       [-1.26465927e+02, -3.09629364e+01],
       [-2.29258154e+02,  1.86087968e+02],
       [-1.29403662e+02, -1.57182355e+02],
       [ 3.29300307e+02,  1.58474695e+02],
       [ 1.03320548e+03, -2.44239741e+01],
       [ 4.40527938e+02,  1.79955002e+02],
       [-2.41951030e+02,  7.84921126e+01],
       [-1.74704346e+02, -5.09136299e+01],
       [-2.85902308e+02,  2.50863540e+02],
       [-1.97517461e+02, -1.05873327e+02],
       [-2.96123773e+02,  1.81400298e+02],
       [-9.80101994e+01, -1.68133594e+01],
       [-1.87227437e+02,  3.66504797e+01],
       [-1.09563321e+02,  2.45938712e+02],
       [ 2.80925120e+02,  2.41604292e+02],
       [-2.78769286e+02, -1.26149937e+02],
       [ 3.11883003e+02, -1.55473110e+02],
       [-2.76241372e+02, -1.89099159e+02],
       [-2.07476289e+02, -5.72385487e+01],
       [ 1.90769431e+03,  5.57263330e+01],
       [-1.72918217e+02, -2.19982704e+02],
       [-2.43776378e+02,  2.48555794e+02],
       [-1.92143790e+02, -2.14749281e+02],
       [ 4.59010879e+02,  6.86062986e+01],
       [-1.21709436e+02,  2.24430386e+02],
       [ 1.00657045e+02,  7.02291112e+01],
       [-4.19113117e+01, -1.67683434e+02],
       [-2.96232456e+02,  1.09338914e+02],
       [-2.40714375e+02,  9.75537843e+01],
       [ 9.32726306e+01, -2.44320250e+02],
       [-3.13792396e+02,  1.97705355e+02],
       [-3.61031478e+02,  1.77793829e+02],
       [ 6.45658267e+01,  7.17815754e+01],
       [-1.71019814e+02, -9.28043983e+01],
       [-2.09314277e+02, -6.13147855e+01],
       [-1.41224994e+02, -2.11703648e+02],
       [ 3.11347069e+02,  2.06792507e+02],
       [-3.41328941e+02, -6.36108176e+01],
       [-2.11722386e+02, -2.50564469e+02],
       [-1.36461312e+02,  2.42857145e+02],
       [-1.03110907e+02, -1.14095600e+02],
       [ 3.00118423e+02, -6.18738139e+01],
       [-2.50422779e+02, -1.84059046e+02],
       [ 6.45406034e+01, -2.72947149e+01],
       [-1.28363730e+02, -1.58144491e+02],
       [ 3.66062043e+02,  2.14994759e+02],
       [ 4.12934075e+02, -2.29478915e+02],
       [-3.44008953e+02,  2.02496811e+02],
       [-3.72473221e+02, -2.60017621e+02],
       [ 9.62929817e+02,  5.58169353e+01],
       [ 1.21274818e+03, -5.92513806e+01],
       [ 7.06199688e+01, -5.40723266e+01],
       [ 3.04098882e+02, -2.10834631e+02],
       [ 5.10879289e+02, -1.26464871e+02],
       [-1.35886952e+02,  1.53804674e+02],
       [ 3.67413769e+02,  6.88196828e+00],
       [-1.55586595e+02, -1.28213200e+02],
       [ 1.75620367e+02, -7.68813196e+01],
       [-1.27798143e+02,  5.20513137e+01],
       [ 7.58692156e+02, -1.91577422e+02],
       [-1.20683370e+02,  4.93346834e+01],
       [-3.20754399e+02, -2.73906199e+00],
       [ 6.00543906e+01,  3.45749973e+01],
       [ 1.40928024e+03,  1.30791250e+02],
       [-3.17950308e+02, -4.76588743e+01],
       [-2.41738543e+02, -1.56389116e+00],
       [-1.36420437e+02,  2.41854196e+02],
       [ 9.05158694e+01, -2.50436662e+02],
       [-3.09764527e+02, -2.51495469e+02],
       [-2.82796956e+02,  7.38459862e+01],
       [ 2.01815909e+02, -1.80914515e+02],
       [ 4.12882576e+02,  9.57817837e+01],
       [-2.29346218e+02, -1.10779997e+01],
       [ 2.00560837e+02,  1.74321026e+02],
       [ 3.69909316e+02,  1.44096326e+02],
       [ 4.93793032e+02, -4.86632818e-02],
       [-2.35988061e+02,  2.96921775e+01],
       [-2.34494826e+00,  9.31182760e+01],
       [ 1.32522004e+02, -5.45550728e-01],
       [-2.63816712e+02, -1.49573015e+02],
       [-2.71883463e+02, -1.97931402e+02],
       [-2.76232583e+02, -2.39143609e+02],
       [-1.90442096e+02, -1.07594606e+02],
       [-2.96176547e+02,  8.25981796e+00],
       [ 6.84257479e+01, -7.41813737e+01],
       [ 3.51352660e+01, -9.25319480e+01],
       [-1.28988533e+02,  2.56163105e+02],
       [ 2.83212343e+02, -6.45542719e+01],
       [-3.08137843e+02,  8.18352727e+01],
       [ 2.55363100e+02,  1.30489174e+02],
       [-1.81710547e+02,  2.38654198e+01],
       [-3.03664920e+02, -1.54171379e+02],
       [-1.11300345e+02,  1.14759274e+02],
       [ 2.02919688e+02, -8.37920231e+01],
       [-1.43796915e+02, -1.22735865e+02],
       [-7.70240278e+01, -4.09861330e+01],
       [-3.20389260e+02,  2.12451566e+02],
       [-1.25129333e+02, -1.38999087e+02],
       [-2.87451404e+02,  1.89752106e+02],
       [-2.47918575e+02, -9.68884808e+01],
       [-1.25121356e+02, -1.89039991e+02],
       [-3.09173208e+02,  5.77743187e+01],
       [ 3.43264724e+02,  5.99550505e+01],
       [-3.33451970e+02, -8.53111858e+01],
       [-2.35884168e+02, -1.22426138e+02],
       [-1.59018542e+02, -1.67378016e+02],
       [-2.15224495e+02,  1.60626231e+02],
       [-2.48647946e+02, -2.88667170e+01],
       [-3.63222601e+02,  1.32669584e+02],
       [ 1.48743895e+01, -1.11359545e+02],
       [ 2.74026093e+02, -1.09955522e+02],
       [-3.29952344e+02,  2.69186139e+01],
       [ 3.24789121e+02, -1.27937046e+02],
       [-4.32755477e+00, -7.04187512e+00],
       [-1.10324458e+01,  1.84843573e+02],
       [-1.76208541e+02, -1.38048637e+02],
       [-4.00733571e+01, -1.63606747e+02],
       [-1.41457970e+02, -6.54395725e+00],
       [-2.07505291e+02, -1.31295417e+02],
       [-1.90863721e+02, -2.21703532e+02],
       [-2.45228710e+02,  8.53621641e+01],
       [-1.76938696e+02, -7.00234614e+01],
       [-3.72973759e+02,  1.26273233e+02],
       [-2.98053560e+01, -1.45175465e+02],
       [-2.39359293e+02, -1.35576269e+02],
       [-3.80613901e+02, -8.22056039e+01],
       [-3.36572358e+02,  1.91781762e+02],
       [-5.27137937e+01,  1.51143949e+02],
       [-2.23366722e+02,  8.92421006e+01],
       [ 4.79439199e+02,  3.34022151e+01],
       [ 9.28450552e+02, -3.26339648e+01],
       [-3.41462009e+02, -2.34752935e+02],
       [-2.97384295e+02,  6.32555441e+01],
       [ 1.10137237e+01, -2.14597053e+02],
       [-2.72011031e+02,  1.04306770e+02],
       [-1.80554718e+02, -2.04275838e+02],
       [-2.46167316e+02,  2.08422914e+02],
       [-5.15902221e+01, -1.26037905e+02],
       [-2.59791579e+02, -7.53521114e+01],
       [ 7.09195602e-01,  2.41359917e+02],
       [ 2.35434451e+02, -2.20593009e+02],
       [ 7.85967712e+02, -4.83675771e+01],
       [-2.43294030e+02,  2.36560725e+02],
       [-1.00719243e+02,  1.75237019e+02],
       [ 6.66722872e+02,  7.99508460e+01],
       [-2.12922234e+02,  3.59569481e+00],
       [-2.40574234e+02,  2.18660052e+02],
       [-2.37095657e+02, -4.24112259e+01],
       [-3.56867407e+01,  1.50823273e+02],
       [-2.12111132e+02, -6.64319220e+01],
       [-3.49037840e+02, -9.59453188e+01],
       [ 2.44187210e+02, -2.14240529e+02],
       [-1.46484611e+02,  1.93410714e+02],
       [-1.33388603e+02, -2.32402788e+02],
       [-1.31846131e+02,  1.27946153e+02],
       [ 2.12703101e+02, -2.83547780e+01],
       [-2.20483154e+02, -2.06876127e+02],
       [-9.76727465e+01,  1.24313762e+02],
       [-2.06839111e+02, -4.82009480e+01],
       [-1.30771198e+02,  1.51010707e+02],
       [-7.38132194e+01, -1.20925459e+02],
       [ 3.84784085e+02, -1.51544732e+02],
       [-2.76741911e+02,  1.97191697e+02],
       [-8.14410033e+00, -1.36299039e+02],
       [ 2.21759472e+02,  7.00921268e+01],
       [ 7.42263798e+02, -1.81228993e+02],
       [-1.71143492e+02,  1.84414118e+02],
       [-2.31497971e+02, -5.71976490e+01],
       [-2.27686003e+02, -1.52121009e+02],
       [-1.32072333e+02, -2.15336320e+02],
       [-2.22372305e+02,  1.14306615e+02],
       [-3.03314995e+02,  1.61096302e+02],
       [-3.14225886e+02,  1.58656540e+02],
       [-2.10558257e+02,  2.18864810e+02],
       [-6.58395191e+01,  2.53699733e+02],
       [-1.82950495e+02,  2.98204581e+01],
       [ 1.43617902e+02, -1.52226861e+02],
       [ 1.82401830e+01, -1.70267790e+02],
       [ 1.04455118e+03,  2.66261936e+02],
       [-1.41332775e+02, -3.45658873e+01],
       [ 2.82759205e+02,  2.70700332e+02],
       [-2.93479386e+02, -1.08730933e+02],
       [-1.03608766e+02, -2.51226713e+02],
       [ 2.38749747e+02,  4.57541872e+01],
       [-6.48638806e+01,  1.54655449e+02],
       [-2.67717455e+02, -2.51811812e+02],
       [-1.37955004e+02, -1.68534762e+02],
       [-2.06818495e+02, -1.73305558e+02],
       [ 6.10787758e+02,  2.01807315e+02],
       [ 2.69937103e+01,  8.52847454e+01],
       [ 7.53696953e+02,  5.74219928e+01],
       [ 5.50032745e+02, -2.98161335e+01],
       [-9.71478221e+01, -1.62896406e+02],
       [-8.17659120e+01,  1.26954304e+02],
       [-2.48259976e+02, -2.12995615e+02],
       [ 4.78837314e+02,  4.83901308e+01],
       [ 1.16924850e+01,  4.26374317e+01],
       [-3.22239953e+01, -1.01675857e+01],
       [-5.70880570e+01, -2.38348860e+02],
       [-2.25614577e+02, -1.04002825e+02],
       [-2.82223354e+02,  2.34001465e+02],
       [-5.95154561e+01,  1.95906992e+02],
       [ 6.99647667e+02, -1.16887229e+02],
       [-2.46806229e+02,  1.99394583e+02],
       [-3.77452546e+02, -1.11098583e+02],
       [-1.90526216e+02, -8.05766266e+01],
       [-2.99072723e+02,  1.30237924e+02],
       [-1.67303279e+02,  1.63551467e+02],
       [ 6.83965743e+01, -1.48237383e+02],
       [-3.17910217e+02, -4.86581362e+01],
       [-1.26571155e+01,  1.00706639e+02],
       [ 2.35022753e+02,  1.13655483e+02],
       [ 2.41154233e+02,  1.08180347e+01],
       [ 9.45261374e+02,  7.21210884e+01],
       [-2.14452920e+01,  7.03297956e+01],
       [-2.56048178e+02, -2.43336244e+02],
       [ 8.52191349e+01,  1.30662145e+02],
       [-3.15394140e+02, -3.65474314e+01],
       [-3.19715870e+02, -3.69440500e+00],
       [ 3.01858824e+02, -2.04915127e+02],
       [-2.17325070e+02, -2.10752512e+02],
       [ 2.26197806e+03,  5.90598243e+00],
       [-3.31151677e+02,  3.18720085e+01],
       [-3.16866950e+02, -7.46371829e+01],
       [-2.95485888e+02,  1.90434067e+02],
       [ 6.70711768e+02,  1.30151259e+02],
       [-9.94641754e+01, -1.79998499e+02],
       [-1.54727492e+02, -7.59676956e-02],
       [ 1.51620029e+02,  4.72549838e+01],
       [-2.56200204e+02,  2.09025466e+02],
       [ 6.50550910e+01,  9.75173139e+00],
       [ 3.01935794e+02,  6.73070317e+01],
       [-8.40853814e+01,  1.34868222e+02],
       [-1.18873771e+02, -2.06490253e+01],
       [-3.13339011e+02, -1.37550444e+02],
       [-2.68932366e+02,  1.02424354e+02],
       [-2.25615248e+01, -2.00933829e+02],
       [ 9.27061435e+01, -2.05307874e+02],
       [ 2.98260022e+02,  5.91529719e+01],
       [-3.44110266e+02, -1.68806061e+02],
       [ 3.09624796e+02,  2.24742254e+02],
       [ 2.15772950e+02,  1.98076386e+01],
       [ 6.19166804e+02,  4.30122902e+01],
       [-2.79250128e+02,  1.35040964e+02],
       [-2.68724711e+02,  4.73927709e+01],
       [-2.63532055e+02,  6.76174042e+01],
       [-1.44548275e+02, -1.78806515e+02],
       [-2.39362467e+02, -1.10559921e+02],
       [ 7.02516558e+01,  4.95657327e+00],
       [-2.02762060e+02, -5.00389380e+01],
       [-2.27974143e+02,  1.54113803e+02],
       [ 3.37923988e+02,  2.17868526e+02],
       [-3.10045594e+02, -2.44500167e+02],
       [ 2.59978178e+02,  2.64782364e+02],
       [-5.15336221e+01,  2.20836830e+01],
       [ 1.88810520e+02, -8.13556306e+01],
       [-1.90774913e+02, -2.45410131e+01],
       [-2.78937681e+02, -7.21132066e+01],
       [-9.33194957e+01, -1.08699125e+02],
       [ 1.59433519e+03, -1.41001907e+02],
       [-4.00588351e+00,  2.34165140e+02],
       [ 1.56663157e+02, -3.57920286e+00],
       [-1.18784099e+02,  1.76508635e+02],
       [-2.71292717e+02,  1.11341259e+02],
       [-2.41778525e+02, -2.49769324e+02],
       [-1.70141047e+02, -8.97664363e+01],
       [-2.54658898e+02,  7.09724339e+01],
       [-4.46029521e+01,  1.73482828e+02],
       [-2.57284295e+02, -1.31969365e+01],
       [-3.73725918e+01, -5.64113267e+01],
       [ 3.54555651e+01, -1.00521676e+02],
       [ 2.59728200e+02, -1.77583656e+02],
       [-9.94423280e+01,  1.93299058e+02],
       [-1.73804284e+02,  7.62199881e+01],
       [-1.64522744e+02,  1.95470046e+01],
       [ 9.49041694e+02,  1.77357457e+02],
       [ 5.56438484e+02,  1.59589737e+02],
       [ 8.54520857e+01, -7.44974210e+01],
       [-2.02708532e+02,  1.23098238e+02],
       [ 6.20024365e+02, -7.80463686e+01],
       [ 1.74746990e+01, -1.26267383e+02],
       [ 2.26461098e+01, -2.30139179e+02],
       [-3.12288017e+02,  3.56352901e+01],
       [-1.82372322e+02,  1.64952343e+02],
       [ 9.76628058e+01, -2.04112421e+02],
       [-1.94887985e+02, -4.67245988e+01],
       [ 8.85405717e+02, -3.23646815e+01],
       [-3.10561827e+02, -7.33376538e+00],
       [-3.14968542e+02,  5.25413380e+01],
       [-1.26039723e+02,  5.81227939e+01],
       [ 1.02855880e+03,  4.14425778e+01],
       [-2.73873205e+02, -2.48055391e+02],
       [-1.54707755e+02, -1.25175602e+02],
       [ 1.95214823e+02, -1.41146987e+02],
       [-8.91702880e+01,  1.86709656e+02],
       [-2.82704016e+02,  2.45987303e+02],
       [ 4.19681020e+02,  7.60348289e+01],
       [ 2.69480211e+02, -1.71191620e+02],
       [ 5.97075122e+02, -2.99285026e+01],
       [ 4.16711196e+02, -9.92260761e+01]])

In [27]:
from sklearn.linear_model import LogisticRegression
logmodel_pca = LogisticRegression()
logmodel_pca.fit(x_train_2,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
y_pred_pca = logmodel_pca.predict(x_test_2)

In [29]:
y_pred_pca

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0], dtype=int8)

In [30]:
confusion_matrix(y_test,y_pred_pca)

array([[35, 21],
       [21, 27]], dtype=int64)

In [31]:
accuracy_score(y_test,y_pred_pca) #reduction in accuracy

0.5961538461538461